package network;

import java.util.LinkedList;

public interface ClientInteractionInterface {
    //
    //	The addClient method is meant to respond to events associated with,
    //		or actions generated by, an Alarm.
    //

    void writeToClient(int command);

    void writeToClient(int command, LinkedList<String> data);

    void writeToClient(int command, LinkedList<String> data, int source);

}
