package network;

public interface Notify {
    //
    //	The takeNotice method is meant to respond to events associated with,
    //		or actions generated by, an Alarm.
    //
    void takeNotice();

    void takeNotice(int command);

    void takeNotice(int command, Object data);
}
