package network;

public interface Notify {
    //
    //	The takeNotice method is meant to respond to events associated with,
    //		or actions generated by, an Alarm.
    //
    public void takeNotice();

    public void takeNotice(int command);

    public void takeNotice(int command, Object data);
}
